### ISSUE TITLE
BiG issue

### ISSUE THREAD

**Issue by DJYK2121** [Burn-One-Studios/B1-Loading#1]
1) loading bar is noT working
2) ha bhai kidhar se dhapi hai
3) deleTe This repo i am begging.

**Comment by Kingsage311** [comment]
Please join our discord for support with this recourse so we can resolve this issue, thank you https://discord.gg/kudbrD6y

**Comment by Horizon35m** [comment]
I am going to close this because there has been no response on the discord or in this issue
